# parameters 

# parameters used by the global estimator
GLOBAL_ESTIMATOR:

  # the local estimator to use
  WAVE_EST_METHOD: "SPATIAL_DFT" # among SPATIAL_DFT, TEMPORAL_CORRELATION, SPATIAL_CORRELATION

  # product characteristics
  DXP: 500.0 # output grid resolution - meters - S2 : 500
  DYP: 500.0 # output grid resolution - meters - S2 : 500
  LAYERS_TYPE: "DEBUG" # among NOMINAL, DEBUG. Allow NetCDF layers selection.
  NKEEP: 3 # number of main waves directions to keep in the product
  
  # window parameters
  WINDOW: 800.0 # thumbnail size - meters
  SM_LENGTH: 10 # smoothing filter size - pixels

  # physical constraints
  MIN_D: 2 #minimal depth - meters
  MIN_T: 3 # minimal wave period - seconds
  MAX_T: 25 # maximal wave period - seconds
  MIN_WAVES_LINEARITY: 0.3 # minimal wave linearity - unitless
  MAX_WAVES_LINEARITY: 0.9 # maximal wave linearity - unitless
  
  # depth inversion
  DEPTH_EST_METHOD: "LINEAR" # among LINEAR
  D_PRECISION: 0.0005 # regression stop criteria - meters
  
#spatial_dft:
SPATIAL_DFT:
  PROMINENCE_MAX_PEAK: 0.3 # find_peaks function tuning - search for the maximal peaks
  PROMINENCE_MULTIPLE_PEAKS: 0.1 # find_peaks function tuning - search for the kkeep max peaks
  UNWRAP_PHASE_SHIFT: False # False if DT<expected wave period (S2 : False)
  MIN_DIR: -180. # min angle for radon transform - degrees
  MAX_DIR: 180. # max angle for radon transform - degrees
  MAX_NDIRS: 360 # nb max of directions for radon transform
  ANGLE_AROUND_PEAK_DIR: 10 # range of angles (-10,+10) to analyse around the spectral peak - degrees
  STEP_T: 0.05 # step for period sampling - seconds - 

#spatial_correlation
SPATIAL_METHOD:
  CORRELATION_MODE: 'full' # np.correlate mode
  AUGMENTED_RADON_FACTOR: 0.01 # radon_augmentation - augment the resolution of the radon transform
  PEAK_POSITION_MAX_FACTOR: 0.8 # peak_position - factor tunning for the maximum peak position

PREPROCESSING:
  PASSBAND:
    LOW_PERIOD: 5
    HIGH_PERIOD: 25

TEMPORAL_METHOD:
  DEBUG_PATH: ""
  PASS_BAND_FILTER: 1
  RESOLUTION:
    SPATIAL: 0.5
    TEMPORAL: 8
    TIME_INTERPOLATION: 0.5
  TEMPORAL_LAG: 1
  PERCENTAGE_POINTS: 5
  TUNING:
    RATIO_SIZE_CORRELATION: 1
    MEDIAN_FILTER_KERNEL_RATIO_SINOGRAM: 0.25
    MEAN_FILTER_KERNEL_SIZE_SINOGRAM: 5
    LOW_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.04
    HIGH_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.2
    MIN_PEAKS_DISTANCE_PERIOD: 5


