#configuration
WAVE_EST_METHOD: "SPATIAL_CORRELATION" # parmi SPATIAL_DFT, TEMPORAL_CORRELATION, SPATIAL_CORRELATION
DEPTH_EST_METHOD: "LINEAR" # parmi LINEAR
NKEEP: 1 # number of main waves directions to keep

#expert
G: 9.81 # g acceleration - m/s2
#wave estimation methods
#wave_common: 
DX: 10 # satellite image resolution - meters
MIN_D: 2 #minimal depth - meters
MIN_T: 5 # minimal wave period - seconds
MAX_T: 25 #maximal wave period - seconds

#spatial_dft:
DT: 1.005 # mean temporal delay between two images - seconds
PROMINENCE_MAX_PEAK: 0.3 # find_peaks function tuning - search for the maximal peaks
PROMINENCE_MULTIPLE_PEAKS: 0.1 # find_peaks function tuning - search for the kkeep max peaks
UNWRAP_PHASE_SHIFT: False # False if DT<expected wave period (S2 : False)
MIN_DIR: -180. # min angle for radon transform - degrees
MAX_DIR: 180. # max angle for radon transform - degrees
MAX_NDIRS: 360 # nb max of directions for radon transform
ANGLE_AROUND_PEAK_DIR: 10 # range of angles (-10,+10) to analyse around the spectral peak - degrees

#depth estimation methods
#depth_common:
D_PRECISION: 0.0005 # regression stop criteria - meters
D_INIT: 1000 # regression - initial value - meters

PREPROCESSING:
  PASSBAND:
    LOW_PERIOD: 5
    HIGH_PERIOD: 25

TEMPORAL_METHOD:
  RESOLUTION:
    SPATIAL: 1
    TEMPORAL: 1
    TIME_INTERPOLATION: 0.5
  TEMPORAL_LAG: 3
  PERCENTAGE_POINTS: 5
  TUNING:
    RATIO_SIZE_CORRELATION: 1
    MEDIAN_FILTER_KERNEL_RATIO_SINOGRAM: 0.25
    MEAN_FILTER_KERNEL_SIZE_SINOGRAM: 5
    LOW_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.04
    HIGH_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.2
    MIN_PEAKS_DISTANCE_PERIOD: 5
  PASS_BAND_FILTER: false
  DEBUG_MODE: true
  DEBUG_PATH: '/home/ad/degoulr'

SPATIAL_METHOD:
  RESOLUTION:
    SPATIAL: 1
    TEMPORAL: 1
    TIME_INTERPOLATION: 0.5
  TEMPORAL_LAG: 3
  PERCENTAGE_POINTS: 5
  TUNING:
    RATIO_SIZE_CORRELATION: 1
    MEDIAN_FILTER_KERNEL_RATIO_SINOGRAM: 0.25
    MEAN_FILTER_KERNEL_SIZE_SINOGRAM: 5
    LOW_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.04
    HIGH_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.2
    MIN_PEAKS_DISTANCE_PERIOD: 5
  PASS_BAND_FILTER: false
  DEBUG_MODE: true
  DEBUG_PATH: '/home/ad/degoulr'
