#configuration
WAVE_EST_METHOD: "SPATIAL_DFT" # parmi SPATIAL_DFT, TEMPORAL_CORRELATION, SPATIAL_CORRELATION
DEPTH_EST_METHOD: "LINEAR" # parmi LINEAR
NKEEP: 3 # number of main waves directions to keep
LAYERS_TYPE: "DEBUG" # parmi NOMINAL ou DEBUG. Permet de selectionner les couches du produit netCDF

#expert
G: 9.81 # g acceleration - m/s2
#wave estimation methods
#wave_common: 
DX: 10 # satellite image resolution - meters
MIN_D: 2 #minimal depth - meters
MIN_T: 5 # minimal wave period - seconds
MAX_T: 25 #maximal wave period - seconds
MIN_WAVES_LINEARITY: 0.3 # minimal wave linearity - unitless
MAX_WAVES_LINEARITY: 0.9 # maximal wave linearity - unitless

#global estimator
DXP: 500.0 # output grid resolution - meters - S2 : 500
DYP: 500.0 # output grid resolution - meters - S2 : 500
WINDOW: 800.0 # thumbnail size - meters - S2 : 800
SM_LENGTH: 10 # smooth filter size - pixels - S2 : 10
STEP_T: 0.05 # step for period sampling - seconds - 

#spatial_dft:
PROMINENCE_MAX_PEAK: 0.3 # find_peaks function tuning - search for the maximal peaks
PROMINENCE_MULTIPLE_PEAKS: 0.1 # find_peaks function tuning - search for the kkeep max peaks
UNWRAP_PHASE_SHIFT: False # False if DT<expected wave period (S2 : False)
MIN_DIR: -180. # min angle for radon transform - degrees
MAX_DIR: 180. # max angle for radon transform - degrees
MAX_NDIRS: 360 # nb max of directions for radon transform
ANGLE_AROUND_PEAK_DIR: 10 # range of angles (-10,+10) to analyse around the spectral peak - degrees

#depth estimation methods
#depth_common:
D_PRECISION: 0.0005 # regression stop criteria - meters

PREPROCESSING:
  PASSBAND:
    LOW_PERIOD: 5
    HIGH_PERIOD: 25

TEMPORAL_METHOD:
  DEBUG_MODE: 0
  DEBUG_PATH: ""
  PASS_BAND_FILTER: 1
  RESOLUTION:
    SPATIAL: 0.5
    TEMPORAL: 8
    TIME_INTERPOLATION: 0.5
  TEMPORAL_LAG: 1
  PERCENTAGE_POINTS: 5
  TUNING:
    RATIO_SIZE_CORRELATION: 1
    MEDIAN_FILTER_KERNEL_RATIO_SINOGRAM: 0.25
    MEAN_FILTER_KERNEL_SIZE_SINOGRAM: 5
    LOW_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.04
    HIGH_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.2
    MIN_PEAKS_DISTANCE_PERIOD: 5

SPATIAL_METHOD:
  DEBUG_MODE: 0
  DEBUG_PATH: ""
  PASS_BAND_FILTER: 1
  RESOLUTION:
    SPATIAL: 0.5
    TEMPORAL: 8
    TIME_INTERPOLATION: 0.5
  TEMPORAL_LAG: 1
  TUNING:
    RATIO_SIZE_CORRELATION: 1
    MEDIAN_FILTER_KERNEL_RATIO_SINOGRAM: 0.25
    MEAN_FILTER_KERNEL_SIZE_SINOGRAM: 5
    LOW_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.04
    HIGH_FREQUENCY_RATIO_TEMPORAL_RECONSTRUCTION: 0.2
    MIN_PEAKS_DISTANCE_PERIOD: 5
